name: Deploy to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Install clojure
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: "1.12.0.1488"
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: ${{ runner.os }}-aoc-clerk-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-aoc-clerk
      - name: Clerk Build
        env:
          AOC_TOKEN: ${{ secrets.AOC_TOKEN }}
          AOC_USER_AGENT: ${{ secrets.AOC_USER_AGENT }}
        run: |
          PATH=$PWD/node_modules/.bin:$PATH clojure -M:nextjournal/clerk
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4
